-- ============================================================================
-- Tabla: public."RemisionesAnuladas"  (Remisiones anuladas — se excluyen del Kardex)
-- ============================================================================
-- RECONSTRUIDO DESDE PRODUCCIÓN el 2026-09-07 (information_schema + pg_constraint).
-- Es DOCUMENTAL: la tabla ya existe en la BD viva. NO re-ejecutar sobre producción.
--
-- Uso: se registra desde reportes.html ("Registrar remisión anulada"). El motor de
--   existencias (js/existencias.js / js/kardex.js) descarta cualquier movimiento
--   cuya remisión aparezca aquí.
-- RLS y policies: ver supabase/rls_data_tables.sql, add_gerente_iaso_role.sql,
--   add_remisionador_to_all_rls.sql.
-- Auditoría: audit_trail.sql + migrations/add_auditoria_nombre_transaccionales.sql.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."RemisionesAnuladas" (
  "id"                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Empresa"               text    DEFAULT ''::text,
  "Remision"              text    DEFAULT ''::text,
  "Producto"              text    DEFAULT ''::text,
  "Presentacion"          text    DEFAULT ''::text,
  "Cantidad"              numeric DEFAULT 0,
  "Fecha"                 text    DEFAULT ''::text,
  "Observaciones"         text    DEFAULT ''::text,
  "Fecha_Registro"        text    DEFAULT ''::text,
  "creado_por"            uuid    REFERENCES auth.users(id),
  "creado_en"             timestamptz DEFAULT now(),
  "modificado_por"        uuid    REFERENCES auth.users(id),
  "modificado_en"         timestamptz,
  "creado_por_nombre"     text,
  "modificado_por_nombre" text
);

-- ALTER TABLE public."RemisionesAnuladas" ENABLE ROW LEVEL SECURITY;  -- ya activo en prod
