-- ============================================================================
-- Tabla: public."Reenvases"  (Salidas a producción / reenvase y traslados de
--                             producto terminado)
-- ============================================================================
-- RECONSTRUIDO DESDE PRODUCCIÓN el 2026-09-07 (information_schema + pg_constraint).
-- Es DOCUMENTAL: la tabla ya existe en la BD viva. NO re-ejecutar sobre producción.
--
-- RLS y policies: ver supabase/rls_data_tables.sql, add_empresa_destino_reenvases.sql,
--   add_gerente_iaso_role.sql, add_remisionador_to_all_rls.sql,
--   migrations/fix_reenvases_select_rls.sql.
-- Estado / retornos: consecutivos_remisiones.sql (Remision_Destino),
--   migrations/add_reenvase_retorno_link.sql (Estado + vínculo con Ingresos).
-- Auditoría: audit_trail.sql + migrations/add_auditoria_nombre_transaccionales.sql.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."Reenvases" (
  "id"                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Empresa"               text    DEFAULT ''::text,
  "Producto"              text    DEFAULT ''::text,
  "Presentacion"          text    DEFAULT ''::text,
  "Cantidad"              integer DEFAULT 0,
  "Remision"              text    DEFAULT ''::text,
  "Fecha"                 text    DEFAULT ''::text,
  "Observaciones"         text    DEFAULT ''::text,
  "Fecha_Registro"        text    DEFAULT ''::text,
  "Planta"                text    DEFAULT ''::text,
  "Bodega"                text    DEFAULT 'Productos Buenos'::text,
  "creado_por"            uuid    REFERENCES auth.users(id),
  "creado_en"             timestamptz DEFAULT now(),
  "modificado_por"        uuid    REFERENCES auth.users(id),
  "modificado_en"         timestamptz,
  "Empresa_Destino"       text    DEFAULT ''::text,
  "Remision_Destino"      text    DEFAULT ''::text,
  "creado_por_nombre"     text,
  "modificado_por_nombre" text,
  "Estado"                text    NOT NULL DEFAULT 'Pendiente'::text,

  CONSTRAINT "Reenvases_Estado_check"
    CHECK ("Estado" = ANY (ARRAY['Pendiente'::text, 'Cerrada'::text]))
);

-- ALTER TABLE public."Reenvases" ENABLE ROW LEVEL SECURITY;  -- ya activo en prod
