-- ============================================================================
-- Tabla: public."KardexNC"  (Movimientos de la bodega de Producto No Conforme)
-- ============================================================================
-- RECONSTRUIDO DESDE PRODUCCIÓN el 2026-09-07 (information_schema + pg_constraint).
-- Es DOCUMENTAL: la tabla ya existe en la BD viva. NO re-ejecutar sobre producción.
--
-- RLS y policies: ver supabase/rls_data_tables.sql, add_gerente_iaso_role.sql,
--   add_remisionador_to_all_rls.sql. Notificaciones: add_notif_kardex.sql.
-- Auditoría: audit_trail.sql + migrations/add_auditoria_nombre_transaccionales.sql.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."KardexNC" (
  "id"                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Fecha"                 text    DEFAULT ''::text,
  "Empresa"               text    DEFAULT ''::text,
  "Producto"              text    DEFAULT ''::text,
  "Presentacion"          text    DEFAULT ''::text,
  "Tipo"                  text    DEFAULT ''::text,
  "Cantidad"              numeric DEFAULT 0,
  "Motivo"                text    DEFAULT ''::text,
  "Observaciones"         text    DEFAULT ''::text,
  "Fecha_Registro"        text    DEFAULT ''::text,
  "Remision"              text    DEFAULT ''::text,
  "creado_por"            uuid    REFERENCES auth.users(id),
  "creado_en"             timestamptz DEFAULT now(),
  "modificado_por"        uuid    REFERENCES auth.users(id),
  "modificado_en"         timestamptz,
  "creado_por_nombre"     text,
  "modificado_por_nombre" text
);

-- Sin CHECK constraints en prod. Valores usados por la app:
--   Tipo   ∈ {Ingreso_NC, Salida_NC}
--   Motivo ∈ {Devolucion_cliente, Retorno_conforme, Traslado_NC, Vencimiento, ...}

-- ALTER TABLE public."KardexNC" ENABLE ROW LEVEL SECURITY;  -- ya activo en prod
