-- ============================================================================
-- Tabla: public."SolicitudMuestras"  (Solicitud de muestras comerciales)
-- ============================================================================
-- RECONSTRUIDO DESDE PRODUCCIÓN el 2026-09-07 (information_schema + pg_constraint).
-- Es DOCUMENTAL: la tabla ya existe en la BD viva. NO re-ejecutar sobre producción.
-- Sirve como fuente de verdad del esquema en el repo (la tabla se creó en su día
-- vía panel/MCP y nunca tuvo script de creación versionado).
--
-- RLS y policies: ver supabase/rls_data_tables.sql, add_comercial_muestras.sql,
--   add_gerente_iaso_role.sql, add_remisionador_to_all_rls.sql,
--   migrations/fix_muestras_comercial_rls.sql.
-- Aprobación: add_aprobacion_muestras.sql / add_modulo_muestras_aprobar.sql.
-- Consecutivo: migrations/add_generar_consecutivo_muestra.sql.
-- Auditoría: audit_trail.sql + migrations/add_auditoria_nombre_transaccionales.sql
--   (triggers trg_auditoria_row y trg_audit_log).
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."SolicitudMuestras" (
  "id"                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Consecutivo"            text    DEFAULT ''::text,
  "Fecha_Solicitud"       text    DEFAULT ''::text,
  "Fecha_Despacho"        text    DEFAULT ''::text,
  "Responsable"           text    DEFAULT ''::text,
  "Municipio"             text    DEFAULT ''::text,
  "Tipo_Cultivo"          text    DEFAULT ''::text,
  "Fecha_Aplicacion"      text    DEFAULT ''::text,
  "Fecha_Seguimiento"     text    DEFAULT ''::text,
  "Remision"              text    DEFAULT ''::text,
  "Objetivo"              text    DEFAULT ''::text,
  "Producto"              text    DEFAULT ''::text,
  "Presentacion"          text    DEFAULT ''::text,
  "Cantidad"              integer DEFAULT 0,
  "Solicitante"           text    DEFAULT ''::text,
  "Autoriza"              text    DEFAULT ''::text,
  "Estado"                text    DEFAULT 'Pendiente'::text,
  "Observaciones"         text    DEFAULT ''::text,
  "Fecha_Registro"        text    DEFAULT ''::text,
  "Empresa"               text    DEFAULT ''::text,
  "Cant_Entregada"        integer DEFAULT 0,
  "Fecha_Entrega"         text    DEFAULT ''::text,
  "Departamento"          text    DEFAULT ''::text,
  "creado_por"            uuid    REFERENCES auth.users(id),
  "creado_en"             timestamptz DEFAULT now(),
  "modificado_por"        uuid    REFERENCES auth.users(id),
  "modificado_en"         timestamptz,
  "Estado_Aprobacion"     text    NOT NULL DEFAULT 'Por aprobar'::text,
  "Aprobada_Por"          text,
  "Fecha_Aprobacion"      timestamptz,
  "Motivo_Rechazo"        text,
  "responsable_id"        uuid    REFERENCES public.usuarios(id) ON DELETE SET NULL,
  "creado_por_nombre"     text,
  "modificado_por_nombre" text,

  CONSTRAINT sm_estado_aprobacion_valido
    CHECK ("Estado_Aprobacion" = ANY (ARRAY['Por aprobar'::text, 'Aprobada'::text, 'Rechazada'::text])),
  CONSTRAINT sm_despacho_requiere_aprobacion
    CHECK (("Estado" <> 'Despachada'::text) OR ("Estado_Aprobacion" = 'Aprobada'::text))
);

CREATE INDEX IF NOT EXISTS idx_muestras_responsable_id
  ON public."SolicitudMuestras" (responsable_id);

-- ALTER TABLE public."SolicitudMuestras" ENABLE ROW LEVEL SECURITY;  -- ya activo en prod
