-- ============================================================================
-- Tabla: public."CambiosMercancia"  (Cambios de mercancía; página devoluciones.html)
-- ============================================================================
-- RECONSTRUIDO DESDE PRODUCCIÓN el 2026-09-07 (information_schema + pg_constraint).
-- Es DOCUMENTAL: la tabla ya existe en la BD viva. NO re-ejecutar sobre producción.
--
-- Modelo: 1 fila por línea de producto, con "Tipo_Linea" = 'CAMBIAR' (entra a
--   bodega) o 'ENTREGAR' (sale de bodega). Se agrupa por "Empresa" + "Consecutivo".
-- RLS y policies: ver supabase/rls_data_tables.sql, add_gerente_iaso_role.sql,
--   add_remisionador_to_all_rls.sql.
-- Columna Cant_Entregada: migrations/add_cant_entregada_to_cambios_mercancia.sql.
-- Auditoría: audit_trail.sql + migrations/add_auditoria_nombre_transaccionales.sql.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."CambiosMercancia" (
  "id"                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Empresa"               text    DEFAULT ''::text,
  "Fecha_Solicitud"       text    DEFAULT ''::text,
  "Fecha_Recogida"        text    DEFAULT ''::text,
  "Consecutivo"           text    DEFAULT ''::text,
  "Cliente"               text    DEFAULT ''::text,
  "NIT"                   text    DEFAULT ''::text,
  "Telefono"              text    DEFAULT ''::text,
  "Correo"                text    DEFAULT ''::text,
  "Num_Factura"           text    DEFAULT ''::text,
  "Fecha_Compra"          text    DEFAULT ''::text,
  "Tipo_Linea"            text    DEFAULT ''::text,
  "Producto"              text    DEFAULT ''::text,
  "Cantidad"              integer DEFAULT 0,
  "Lote_Vencimiento"      text    DEFAULT ''::text,
  "Razon_Cambio"          text    DEFAULT ''::text,
  "Fecha_Cambio"          text    DEFAULT ''::text,
  "Valor_Cliente"         numeric DEFAULT 0,
  "Valor_Empresa"         numeric DEFAULT 0,
  "Observaciones"         text    DEFAULT ''::text,
  "Estado"                text    DEFAULT 'Pendiente'::text,
  "Fecha_Registro"        text    DEFAULT ''::text,
  "Remision_Ingreso"      text    DEFAULT ''::text,
  "Bodega_Ingreso"        text    DEFAULT 'Productos Buenos'::text,
  "Fecha_Ingreso"         text    DEFAULT ''::text,
  "Remision_Salida"       text    DEFAULT ''::text,
  "Bodega_Salida"         text    DEFAULT 'Productos Buenos'::text,
  "Fecha_Salida"          text    DEFAULT ''::text,
  "creado_por"            uuid    REFERENCES auth.users(id),
  "creado_en"             timestamptz DEFAULT now(),
  "modificado_por"        uuid    REFERENCES auth.users(id),
  "modificado_en"         timestamptz,
  "Cant_Entregada"        numeric DEFAULT 0,
  "creado_por_nombre"     text,
  "modificado_por_nombre" text
);

-- Sin CHECK constraints en prod. Valores usados por la app:
--   Estado      ∈ {Pendiente, Parcial, Cerrado}   (+ badge Completado/Anulado en UI)
--   Tipo_Linea  ∈ {CAMBIAR, ENTREGAR}

-- ALTER TABLE public."CambiosMercancia" ENABLE ROW LEVEL SECURITY;  -- ya activo en prod
