-- Migración: importar clientes PARCELAR desde Excel maestro
-- Ejecutar en Supabase SQL Editor

-- 1) Agregar columnas nuevas
ALTER TABLE "ClientesUnicos" ADD COLUMN IF NOT EXISTS "Lista_Precio" text DEFAULT '';
ALTER TABLE "ClientesUnicos" ADD COLUMN IF NOT EXISTS "Direccion_Envio" text DEFAULT '';

-- 2) Limpiar clientes PARCELAR existentes (antes de cambiar indice)
DELETE FROM "ClientesUnicos" WHERE "Nombre_Empresa" = 'PARCELAR';

-- 3) Cambiar indice unico para permitir multiples sucursales por cliente
DROP INDEX IF EXISTS "ClientesUnicos_empresa_nit_uq";
CREATE UNIQUE INDEX IF NOT EXISTS "ClientesUnicos_empresa_nit_mun_uq"
  ON "ClientesUnicos" ("Nombre_Empresa", "Identificacion", "Municipio")
  WHERE "Identificacion" IS NOT NULL AND "Identificacion" != '';

-- 4) Insertar clientes PARCELAR desde Excel maestro

INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA CADENA SAS', '900983749-1', 'NIT', '3229475308', 'calle 4 # 7a-26', 'almacen zipaquira', 'Zipaquirá', 'CUNDINAMARCA', 'PARCELAR', '100000000', '120', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA CADENA SAS', '900983749-1', 'NIT', '3229475308', 'calle 4 # 7a-26', 'almacen la paz zipaquira', 'la paz ( zipaquira)', 'CUNDINAMARCA', 'PARCELAR', '', '120', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA CADENA SAS', '900983749-1', 'NIT', '3229475308', 'calle 4 # 7a-26', 'almacen cogua', 'cogua', 'CUNDINAMARCA', 'PARCELAR', '', '120', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA CADENA SAS', '900983749-1', 'NIT', '3229475308', 'calle 4 # 7a-26', 'almacen subachoque', 'subachoque', 'CUNDINAMARCA', 'PARCELAR', '', '120', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA CADENA SAS', '900983749-1', 'NIT', '3229475308', 'calle 4 # 7a-26', 'CRA 7 7 98', 'Facatativá', 'CUNDINAMARCA', 'PARCELAR', '', '120', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA CADENA SAS', '900983749-1', 'NIT', '3229475308', 'calle 4 # 7a-26', 'almacen tausa', 'Tausa', 'CUNDINAMARCA', 'PARCELAR', '', '120', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA CADENA SAS', '900983749-1', 'NIT', '3229475308', 'calle 4 # 7a-26', 'almacen ubate', 'ubate', 'CUNDINAMARCA', 'PARCELAR', '', '120', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA DE LA ONCE SAS', '901390224-3', 'NIT', '3105598846', 'CL 11 15 A 38', 'CL 11 15 A 38', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '5000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA EL MERCHANERO SAS', '901267767-5', 'NIT', '3133291542', 'VDA MERCHAN CENTRO', 'calle 7# 8-23 esquina centro', 'Saboyá', 'boyaca', 'PARCELAR', '12000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA LA PLAYA SAS', '900889093-5', 'NIT', '3142401003', 'VDA BOITIVIA SEC LA PLAYA', 'est de servicio la playabrio', 'Sesquilé', 'cundinamarca', 'PARCELAR', '15000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGRICOLA LOS PINOS SAS', '800159028-1', 'NIT', '6018209914', 'CL 7 1 50', 'almacen Madrid', 'Madrid', 'CUNDINAMARCA', 'PARCELAR', '5000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROALIANZA HYG SAS', '901555789-2', 'NIT', '3108027376', 'CR 7 15A 54', '', 'Villa De San Diego De Ubate', 'cundinamarca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROANDINA GS SAS', '900429519-8', 'NIT', '3114821047', 'CR 5 7 11', 'choconta cund', 'Chocontá', 'cundinamarca', 'PARCELAR', '10000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROCENTRO LA PALMA', '1053343656-7', 'NIT', '3112771793', 'MERCHAN SECTOR LA JABONERA', 'calle 7# 8-23 esquina centro', 'Saboyá', 'boyaca', 'PARCELAR', '10000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROCENTROJH SAS', '901480773-1', 'NIT', '3166814545', 'CL 11 15 53', 'CL 11 15 53', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '8000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROCES SAS CENTRO DE SOLUCIONES AGROPECUARIAS', '901559526-0', 'NIT', '3122913206', 'CR 3 3 48 BRR EL SOCOREERO', 'CR 3 3 48 BRR EL SOCOREERO', 'Buesaco', 'nariño', 'PARCELAR', '30000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROINSUMOS LA ISLA SAS', '901501543-6', 'NIT', '3115067585', 'CR 20 12 21', 'CR 20 12 21', 'Sogamoso', 'boyaca', 'PARCELAR', '5000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROINSUMOS MENDEZ TAUTA SAS', '901397882-1', 'NIT', '3186138368', 'CR 5 5 02', 'san bernardo cund', 'San Bernardo', 'cundinamarca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROMOCHUELO SAS', '901633612-2', 'NIT', '3117181596', 'KM8 VIA PASQUILLA', 'mochuelo bajo bogota', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '50000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROMOCHUELO SAS', '901633612-2', 'NIT', '3117181596', 'KM8 VIA PASQUILLA', 'pasquilla pogota', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '50000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROMOCHUELO SAS', '901633612-2', 'NIT', '3117181596', 'KM8 VIA PASQUILLA', 'quiba bogota', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '50000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA CARUPA SU ALIADO SAS', '901819788-1', 'NIT', '3142534220', 'CR 2 3 90', 'almacen carmen de carupa', 'Carmen De Carupa', 'CUNDINAMARCA', 'PARCELAR', '10000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA HOLSTEIN SAS', '832003502-8', 'NIT', '3108574730', 'CR 7 15A92', 'almacen Ubate', 'Villa De San Diego De Ubate', 'CUNDINAMARCA', 'PARCELAR', '5000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'bogota', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'sibate "al lado ara"', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'vda la 22 granada', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'vda san raimuindo silvania cund', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'vda subia silvania cund', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'av de las palmas 13 05 fgga cund', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'arbelaez', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'san bernardo cund', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'vda la unchia san bernardo cund', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'venecia', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA INTERNACIONAL SAS "AGROINTER"', '860522063-4', 'NIT', '3203039965', 'AV CR 45 168 21 AUTOPISTA NORTE', 'pasca plaza principal', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '100000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPECUARIA LA ESPERANZA RRR SAS', '900878589-9', 'NIT', '3022316066', 'CR 3 5 78', 'CR 3 5 78', 'Quebradanegra', 'cundinamarca', 'PARCELAR', '10000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROPSALINAS ANGELA PATRICIA CEPEDA SALINAS', '1019004848', 'CC', '3232101812', 'CL 1 2 41', 'CL 1 2 41', 'Guaduas', 'cundinamarca', 'PARCELAR', '2000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROSAES SAS. " DENNIS BRAND DUQUE "', '901813939-8', 'NIT', '3134791075', 'CL 5B 25 46 CASA 100', 'la que lecliente indique', 'Villavicencio', 'meta', 'PARCELAR', '150000000', '240', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROVERT SAS', '901067015-7', 'NIT', '3058816728', 'KM 18 VIA BOGOTA MOSQUERA PAR INDUSTRIAL SABANAPH', 'almacen subia', 'Mosquera', 'cundinamarca', 'PARCELAR', '5000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AGROZAM FACATATIVA', '901042166-2', 'NIT', '3217563772', 'CR 1 7 62', 'almacen Facatativa', 'Facatativá', 'CUNDINAMARCA', 'PARCELAR', '', '120', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('ALMACEN AGRICOLA AGRICENTRO SAS', '832009053-1', 'NIT', '3112574381', 'VDA PUEBLO VIEJO SECTOR LAS MERCEDES KM 1 VIA CHIA', 'almacen cota', 'Cota', 'CUNDINAMARCA', 'PARCELAR', '10000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('ALMACEN AGRICOLA LA QUINTA SAS', '901505874-7', 'NIT', '3142351107', 'CR 5 2 92', 'villapinzon cund', 'Villapinzón', 'cundinamarca', 'PARCELAR', '15000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('ALMACEN EL AMIGO SAS', '832005100-1', 'NIT', '3158998195', 'CR 4 6 87', 'villapinzon cund', 'Villapinzón', 'cundinamarca', 'PARCELAR', '3000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('ALVARADO FORERO OSCAR YESID', '7124528-5', 'NIT', '3133972477', 'CL 3 2 68', 'calle 3 # 2-68', 'Sutamarchán', 'boyaca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AREVALO CASTILLO MYRIAM YANETH', '40031087', 'CC', '3115311560', 'CLL 20 #14-47', '', 'Tunja', 'boyaca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('AVILA SANCHEZ NESTOR ROLANDO', '1057214047', 'CC', '0', 'CR 9 7 37 BRR LOS OLIVOS', '', 'Villa De Leyva', 'boyaca', 'PARCELAR', '10000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('CASTELLANOS SANCHEZ PEDRO ADALBERTO', '7316692-1', 'NIT', '3103039442', 'CL 9 4 5 4', '', 'Simijaca', 'CUNDINAMARCA', 'PARCELAR', '20000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('COMERCIALIZADORA DE INSUMOS PA LA FINCA SAS', '900444743-4', 'NIT', '3118452437', 'CR 1 9 39', '', 'Guatavita', 'CUNDINAMARCA', 'PARCELAR', '3000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('COMERCIALIZADORA MACRI SAS', '900679623-8', 'NIT', '3213701546', 'CR 9A 7 44', 'sibate parque principal', 'Sibaté', 'CUNDINAMARCA', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('COMERCIALIZADORA NUEVA VISION AGROPECUARIA SAS', '832005340-0', 'NIT', '3124388002', 'CR 7 15 64', 'almacen ubate', 'Villa De San Diego De Ubate', 'CUNDINAMARCA', 'PARCELAR', '100000000', '120', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('COMPAÑÍA AGRICOLA TOLIMENSE SAS', '901986272-6', 'NIT', '3223261762', 'CLL 37A 9 70', 'calle 7 # 4-70 chicoral', 'chicoral', 'tolima', 'PARCELAR', '10000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('CORREDOR ALIADO JUAN CARLOS', '7128002', 'CC', '3208520512', 'CRA 3 #4-46', '', 'Sáchica', 'boyaca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('CUBILLOS JIMENEZ DIDIMO ALEXANDER', '82393300', 'CC', '3156303297', 'CLL 22 8 39 CASA 7', 'CLL 22 8 39 CASA 7', 'Fusagasugá', 'cundinamarca', 'PARCELAR', '2000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('DIAZ BOHORQUEZ AGRODIAZ DE COLOMBIA DEHISY CRISTINA', '52270251', 'CC', '3166246402', 'CL 6 N 2 65 - Centro', '', 'Sutamarchán', 'boyaca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('DIAZ RODRIGUEZ ZULMA MILENA', '52888194', 'CC', '3133956529', 'CL 2 3 03', 'venecia cund parque principal', 'Venecia', 'cundinamarca', 'PARCELAR', '12000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('DISTRIBUIDORA AGRICOLA DEL SUMAPAZ SAS', '900086526-6', 'NIT', '0', 'CL 19B 6 40', '', 'Fusagasugá', 'cundinamarca', 'PARCELAR', '', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('DISTRIBUIDORA DE INSUMOS AGROPECUARIOS DEL HATO SAS', '901813137-8', 'NIT', '3103563717', 'CARRERA 6 # 13A -22', 'CARRERA 6 # 13A -22', 'Málaga', 'santander', 'PARCELAR', '20000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('DUQUE ARAQUE HERNAN ANTONIO', '70030033', 'CC', '6436814', 'CR 73 A 135 20 CONJ GRATAMIRA', 'CR 73 A 135 20 CONJ GRATAMIRA', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '20000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('EL ESTABLO COLOMBIA SAS', '901488581-0', 'NIT', '3009122041', 'CRA 7 5 51 CENTRO', 'CRA 7 5 51 CENTRO', 'Villeta', 'cundinamarca', 'PARCELAR', '10000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('ENCISO AVILA MARINA', '41578295-6', 'NIT', '6018640500', 'CR 5 14A 26', 'almacen cota', 'Cota', 'CUNDINAMARCA', 'PARCELAR', '3000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('EXIAGRICOLA J D LTDA', '830119428-2', 'NIT', '3123503966', 'CR 20 A 73 01', 'CR 20 A 73 01', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '10000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('FITOFERTIL SAS', '900982097-1', 'NIT', '3133494351', 'CRA 5 # 5-84', 'villapinzon', 'Villapinzón', 'cundinamarca', 'PARCELAR', '30000000', '120', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('GALINDO GARCIA JORGE ELIECER', '11510798-7', 'NIT', '3132610087', 'CL 8B 10 04 BRR SANTANA', 'almacen facatativa', 'Mosquera', 'CUNDINAMARCA', 'PARCELAR', '3000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('GARCIA GARZON LUIS CARLOS', '1077145788', 'CC', '0', 'CL 3# 6-50 PLAZA', '', 'Villapinzón', 'CUNDINAMARCA', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('GRUPO SIEMSO SAS', '901852586-8', 'NIT', '3175405799', 'CR 34B 23 65 SUR', '', 'Neiva', '', 'PARCELAR', '', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('GRUPO TECNOAGRO SAS', '901376672-1', 'NIT', '3184374719', 'CL 5 2 77', '', 'Sáchica', 'Boyaca', 'PARCELAR', '5000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('HORTALIZAS AGROFER SAS', '902047368-1', 'NIT', '3208578306', 'FCA PIEDRA LARGA vda CANOA SANEZ', 'almacen soacha', 'SOACHA', 'CUNDINAMARCA', 'PARCELAR', '2000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('HORTALIZAS EL MANA SAS', '901256777-1', 'NIT', '3138694258', 'FCA PIEDRA LARGA VDA CANOA SAENZ', 'almacen soacha', 'Mosquera', 'CUNDINAMARCA', 'PARCELAR', '10000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('IASO INSUMOS AGROPECUARIOS SOSTENIBLES SAS', '901924101-1', 'NIT', '3103616741', 'AV TRONCAL DE OCCIDENTE #11E-03', 'AV TRONCAL DE OCCIDENTE #11E-03', 'Mosquera', 'cundinamarca', 'PARCELAR', '30000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('INVERSIONES AGRICOLAS SAN MARTIN SAS', '900617062-0', 'NIT', '3125363500', 'CR 7 8 09', 'almacen zipaquira', 'Zipaquirá', 'CUNDINAMARCA', 'PARCELAR', '5000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('JANAGRO DISTRIBUCIONES SAS', '901445314-6', 'NIT', '3103234095', 'MANZANA B CASA 12 BARRIO SAN FRNCISCO AV AMBALA CONTIGUO GLORIETA VERGEL', 'Cr 10A CON 129-26 BARRIO MALABAR', 'Ibagué', 'tolima', 'PARCELAR', '30000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('LA FINCA AGROPECUARIA PARA EL CAMPO SAS', '901568256-5', 'NIT', '3102404991', 'CR 3 7 24', 'CR 3 7 24', 'Yacopí', 'cundinamarca', 'PARCELAR', '2000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('LANCHEROS LIDA  JOHANA', '35251076', 'CC', '3134613851', 'CR 5 3 10 41', 'cabrera cund', 'Fusagasugá', 'cundinamarca', 'PARCELAR', '5000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('LINARES MARQUEZ LUZ STELLA', '39623629', 'CC', '3125225230', 'CRA 8N 15F 13', 'CRA 8N 15F 13', 'Facatativá', 'cundinamarca', 'PARCELAR', '2000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('LOPEZ CUERVO JOSE RICARDO', '80468373', 'CC', '3002668058', 'VDA QUINCHA FCA VILLA NUEVA', 'villapinzon (al lado del comando de la policia)', 'Villapinzón', 'cundinamarca', 'PARCELAR', '30000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('LOPEZ RODRIGUEZ CARLOS JULIO', '74245482', 'CC', '3133823308', 'SANTA', '', 'Santa Sofía', 'boyaca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('MALAGON MARTHA YOLANDA', '23315189', 'CC', '3133775436', 'AV 3 #5-85', '', 'Arcabuco', 'boyaca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('MAZORCA VALERO WILFREDO ANTONIO', '74150689', 'CC', '0', 'CL 11 9 68 BRR LAS FERIAS', '', 'Chiquinquirá', 'boyaca', 'PARCELAR', '10000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('MEJIA TRIANA FRANCY YASMIN', '52654461', 'CC', '3133910156', 'CR 7 3 116', 'CR 7 3 116', 'Villeta', 'cundinamarca', 'PARCELAR', '15000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('MISAKGRO', '901472748-3', 'NIT', '3115746582', 'CRA 5 ESTE #20-69 CENTRO EMPRESARIAL EL CABRERO', 'almacenn funza', 'Mosquera', 'CUNDINAMARCA', 'PARCELAR', '5000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('MORENO CLARA INES', '24197076', 'CC', '31146215018', 'VEREDA PUNTA DEL LLANO', '', 'Sotaquirá', 'boyaca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('NAGLES ZAPATA INGRID JOHANA', '1123059650', 'CC', '3227434051', 'CL PRINCIPAL 4 33 IPM', 'RANCHO GANADERO', 'La Sierra', 'cundinamarca', 'PARCELAR', '5000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('NARVAEZ BARRERA OSCAR DARIO', '1086924421', 'CC', '3135899029', 'BRR LAS FERIAS', 'BRR LAS FERIAS', 'Caparrapí', 'cundinamarca', 'PARCELAR', '3000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('NIÑO GARAY DIEGO ALEJANDRO', '1070968224', 'CC', '3106968122', 'TV 1S 25C ESTE BRR CARTAGENITA', 'almacen cartagenita', 'Facatativá', 'CUNDINAMARCA', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('PABON MEDINA ALEX JAIR', '1295450', 'CC', '3186507106', 'VIA JAGUITO LA MARIA', '', 'Santander De Quilichao', '', 'PARCELAR', '', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('PADILLA ORTIZ ZULMA CRISTINA', '1061654023', 'CC', '3174663828', 'VDA CHIMBE FCA MIRANDA', 'VDA CHIMBE FCA MIRANDA', 'Albán', 'cundinamarca', 'PARCELAR', '3000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('PEDRAZA GARCIA DIANA MAYERLI', '1000784737-4', 'CC', '3227165012', 'TV 3 4 49 VIA PASQUILLA', 'pasquilla bogota', 'Bogota D.C.', 'cundinamarca', 'PARCELAR', '5000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('PINZON CERINZA CARLOS', '1053611291', 'CC', '3209517482', 'CRA 8 N 5 -56', 'CRA 8 N 5 -56', 'Tuta', 'boyaca', 'PARCELAR', '15000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('PULGARIN LOZANO ANA FLOR', '20705077', 'CC', '3105611358', 'CRA 3 2A 50', 'CRA 3 2A 50', 'La Peña', 'cundinamarca', 'PARCELAR', '20000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('RAMIREZ BONILLA CARLOS ANDRES', '80282454', 'CC', '3125867890', 'VEREDA NARANJAL', 'VEREDA NARANJAL', 'Villeta', 'cundinamarca', 'PARCELAR', '2000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('RAMIREZ RUBIELA MEJIA', '21082568', 'CC', '3215436540', 'BRR CENTRO CR3 5 44', 'BRR CENTRO CR3 5 44', 'Útica', 'cundinamarca', 'PARCELAR', '2000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('SALAZAR ARDILA LUZ ADRIANA', '63533760', 'CC', '3123207475', 'CR 16 12 26 AP 101 BRR CABECERA', '', 'sogamoso', 'boyaca', 'PARCELAR', '', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('SAVITOL-CROP SAS', '901746562-8', 'NIT', '3118785680', 'TRONCAL DE OCCIDENTE 11E-03E PARQUE AGROINDUSTRIAL DE LA SABANA', 'km 2 autopista medellin parque empresarial oikos la florida bod. 12', 'cota', 'cundinamarca', 'PARCELAR', '30000000', '120', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('SERVIAGRO PASCA SAS', '901555328-0', 'NIT', '3104605163', 'TV 5 3 21 BRR FLANDES', 'pasca barrio flandes', 'Pasca', 'cundinamarca', 'PARCELAR', '50000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('TELLEZ RODRIGUEZ MASSIEL PAOLA', '1057488459', 'CC', '310579478', 'CR 11 # 2-49', 'calle 1 # 4-166', 'villeta', 'cundinamarca', 'PARCELAR', '10000000', '60', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('TODOCAMPO FAJARDO SAS', '901737428-1', 'NIT', '3125460551', 'AUT BOGOTA - GIRARDOT KM 32 VDA SAN REIMUNDO', 'vda san raimundo silvania', 'Granada', 'cundinamarca', 'PARCELAR', '2000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('TRIANA PALACIO DIEGO MAURICIO', '80280896', 'CC', '3143475918', 'CL 4 3 25 IMP LA MAGDALENA', 'CL 4 3 25 IMP LA MAGDALENA', 'la magdalena', 'cundinamarca', 'PARCELAR', '5000000', '60', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('VALDERRAMA RATIVA EPIGMENIO', '19058872', 'CC', '3144447613', 'CL 16 A 6 79', 'almacen cota', 'Cota', 'CUNDINAMARCA', 'PARCELAR', '3000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('VARGAS AGUILERA INGRITH YOHANA', '24134755', 'CC', '3112050379', 'CR 9 7A 16 BRR LOS OLIVOS', '', 'Tunja', 'boyaca', 'PARCELAR', '15000000', '90', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('VARGAS MOLLENO MAURICIO', '72326554', 'CC', '3112062811', 'CLL 9 #7-18', '', 'Ramiriquí', 'boyaca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('ZAMBRANO SANCHEZ COMERCIALIZADORA AGROPECUARIA AMIA ANA CONSUELO', '1056029656-2', 'NIT', '3134848169', 'URB JUAN PABLO SEGUNDO 7-175', 'calle 7# 8-23 esquina centro', 'Chiquinquirá', 'boyaca', 'PARCELAR', '12000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('SAMVET S.A.S', '901675165-1', 'NIT', '3202624680', 'CL 5 # 12-48', 'CL 5 # 12-48', 'Tauramena', 'casanare', 'PARCELAR', '5000000', '60', 'Mayorista');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('LEOAGRO JC SAS', '901943667---7', 'NIT', '3104769036', 'DG 26 NO. 2 C 27', 'fusagasuga (3222002058)', 'Fusagasugá', 'cundinamarca', 'PARCELAR', '10000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('QUIMICOS ESPECIALES Y SILICONAS SAS', '901310216---2', 'NIT', '3204844375', 'CL 78 SUR 18B 94', 'SIBATE', 'sibate', 'cundinamarca', 'PARCELAR', '5000000', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('EDILSON DIAZ PATIÑO', '4276421', 'CC', '3115824268', 'CL 5 #2-33', '', 'tibana', 'boyaca', 'PARCELAR', '', '90', 'Dealer');
INSERT INTO "ClientesUnicos" ("Cliente", "Identificacion", "Tipo_Identificacion", "Telefono", "Direccion", "Direccion_Envio", "Municipio", "Departamento", "Nombre_Empresa", "Cupo_Credito", "Plazo_Pago", "Lista_Precio") VALUES ('NILSON JULIAN CARRILLO MORALES', '7182039---2', 'CC', '3212021989', 'CR 16  4 33B', '', 'tunja', 'boyaca', 'PARCELAR', '12000000', '90', 'Dealer');
