-- ════════════════════════════════════════════════════════════
-- Tabla: ListaPrecios
-- Almacena listas de precios por empresa y tipo (Dealer, Mayorista, etc.)
-- ════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS "ListaPrecios" (
  id bigserial PRIMARY KEY,
  "Empresa" text NOT NULL,
  "Tipo_Precio" text NOT NULL,
  "Producto" text NOT NULL,
  "Precio" numeric NOT NULL DEFAULT 0,
  "creado_por" uuid,
  "modificado_por" uuid,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- Índice para búsqueda rápida por empresa + tipo + producto
CREATE INDEX IF NOT EXISTS idx_lista_precios_empresa_tipo
  ON "ListaPrecios" ("Empresa", "Tipo_Precio");

CREATE INDEX IF NOT EXISTS idx_lista_precios_producto
  ON "ListaPrecios" ("Producto");

-- Unique constraint para evitar duplicados
ALTER TABLE "ListaPrecios"
  ADD CONSTRAINT uq_lista_precios_empresa_tipo_producto
  UNIQUE ("Empresa", "Tipo_Precio", "Producto");

-- RLS
ALTER TABLE "ListaPrecios" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ListaPrecios_select" ON "ListaPrecios"
  FOR SELECT USING (true);

CREATE POLICY "ListaPrecios_insert" ON "ListaPrecios"
  FOR INSERT WITH CHECK (true);

CREATE POLICY "ListaPrecios_update" ON "ListaPrecios"
  FOR UPDATE USING (true);

CREATE POLICY "ListaPrecios_delete" ON "ListaPrecios"
  FOR DELETE USING (true);

-- ════════════════════════════════════════════════════════════
-- Datos iniciales: Lista de precios RESO — Dealer
-- ════════════════════════════════════════════════════════════

INSERT INTO "ListaPrecios" ("Empresa", "Tipo_Precio", "Producto", "Precio") VALUES
-- RESO products
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GROW GREEN SP X BIDON 20 LITROS', 3204887),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GROW GREEN SP X GALON', 640977),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GROW GREEN SP X LITRO', 166654),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'IKASOL X BIDON 20 LITROS', 4026510),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'IKASOL X 250 ML', 55393),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'IKASOL X GALON', 810692),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'IKASOL X LITRO', 205373),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ARACK GREEN X GALON', 580230),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ARACK GREEN X 20 LITROS', 2874150),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ARACK GREEN X 250 ML', 45405),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ARACK GREEN X 500 ML', 78300),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ARACK GREEN X LITRO', 147756),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'BA-BOR-ZINC X BIDON 20 LITROS', 2047567),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'BA-BOR-ZINC X 250 ML', 37390),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'BA-BOR-ZINC X GALON', 416641),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'BA-BOR-ZINC X 500 ML', 58832),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'BA-BOR-ZINC X LITRO', 110392),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CALIMAN X GALON', 128196),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CALIMAN X CANECA 10 LITROS', 291141),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CALIMAN X BIDON 20 LITROS', 618980),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CALIMAN X LITRO', 34720),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GEON3 X BIDON 20 LITROS', 1914300),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GEON3 X 250 ML', 27540),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GEON3 X GALON', 388260),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GEON3 X 500 ML', 51900),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GEON3 X LITRO', 99765),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GROW GREEN X LITRO', 138920),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GROW GREEN X 250 ML', 38780),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GROW GREEN X 500 ML', 74856),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GROW GREEN X GALON', 544887),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GROW GREEN X BIDON 20 LITROS', 2697435),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'JABOTAN X 20 LITROS', 507060),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'JABOTAN X GALON', 106811),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'JABOTAN X LITRO', 29403),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NEEM GREEN X 500 ML', 83387),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NEEM GREEN X BIDON 20 LITROS', 3026876),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NEEM GREEN X 250 ML', 44943),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NEEM GREEN X GALON', 614278),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NEEM GREEN X LITRO', 156685),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'THYME GREEN X BIDON 20 LITROS', 3026876),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'THYME GREEN X 250 ML', 44943),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'THYME GREEN X LITRO', 156685),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'THYME GREEN X GALON', 614278),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'THYME GREEN X 500 ML', 83387),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CALCI-TECH X GALON 5 LITROS', 85050),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CALCI-TECH X LITRO', 24300),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CALCI-TECH BIDON X 20 LITROS', 357750),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GENIUS-TECH X 250 ML', 34492),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GENIUS-TECH X GALON 5 LITROS', 494100),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GENIUS-TECH X BIDON 20 LITROS', 2443500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GENIUS-TECH X LITRO', 127008),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'MEKA-TECH X 250 ML', 560250),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'MEKA-TECH X GALON 5 LITROS', 117450),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'MEKA-TECH X LITRO', 32400),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NITRO-TECH X GALON 5 LITROS', 90450),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NITRO-TECH X LITRO', 25650),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NITRO-TECH X BIDON 20 LITROS', 425250),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'PROTO TECH X GALON 5 LITROS', 128250),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'PROTO TECH X LITRO', 35100),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'PROTO TECH X BIDON 20 LITROS', 614250),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'YODO X BIDON 20 LTS', 739791),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'YODO X GALON', 153358),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'YODO X LITRO', 41039),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'YODO X 250 ML', 14310),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'YODO X 500 ML', 22228),
-- GREEN products (under RESO empresa)
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN AMINO X BIDON 20 LITROS', 829227),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN AMINO X GALON', 175228),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN AMINO X LITRO', 46439),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN AMINO X 250 ML', 13365),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN FOS X 20 LITROS', 988188),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN FOS X 500 ML', 28755),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN FOS X GALON', 203037),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN FOS X LITRO', 53459),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN FOS X 250 ML', 17415),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN K X 500 ML', 34560),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN K X BIDON 20 LITROS', 1062437),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN K X GALON', 218887),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN K X LITRO', 57172),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN K X 250 ML', 18360),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CORRECTOR X 250 ML', 8580),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CORRECTOR X BIDON 20LT', 597624),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CORRECTOR X GALON', 121445),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CORRECTOR X LITRO', 33001),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN VAX X 500 ML', 50700),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN VAX X LITRO', 91000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CA-L X CANECA 10 LITROS', 308000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CA-L X CANECA 20 LITROS', 614000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CA-L X GALON', 128200),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CA-L X LITRO', 34800),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CA-L X CANECA 60 LITROS', 1810000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN 40F X BIDON 20 LITROS', 2697500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN 40F X 250 ML', 38800),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN 40F X 500 ML', 73500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN 40F X GALON', 545000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN 40F X LITRO', 138950),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'AKAR GREEN X 250 ML', 40900),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'AKAR GREEN X 500 ML', 79200),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'AKAR GREEN X BIDON 20 LITROS', 2874300),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'AKAR GREEN X GALON', 580300),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'AKAR GREEN X LITRO', 147800),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CU-ILL X BIDON 20 LITROS', 467800),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CU-ILL X GALON', 95150),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN CU-ILL X LITRO', 24300),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'PEGASSO TOP X BIDON 20 LITROS', 354000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'PEGASSO TOP X GALON', 71500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'PEGASSO TOP X LITRO', 18600),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'PEGASSO TOP X CANECA 60 LITROS', 998400),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NEMOCAP X BIDON 20 LITROS', 1914300),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NEMOCAP X 500 ML', 52000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NEMOCAP X GALON', 388500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NEMOCAP X LITRO', 99800),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NEMOCAP X BIDON 60 LITROS', 5698000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'JABOTAN EXPORTACION X BIDON 20 LITROS', 677800),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'JABOTAN EXPORTACION X GALON', 142000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'JABOTAN EXPORTACION X LITRO', 39200),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'JABOTAN EXPORTACION X BIDON 60 LITROS', 2020000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN YODO X BIDON 20 LITROS', 739800),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN YODO X 250 ML', 14300),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN YODO X GALON', 153400),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN YODO X LITRO', 41000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN YODO X 500 ML', 25000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN MOLUS-KILL X 250 ML', 37400),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN MOLUS-KILL X 500 ML', 72400),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN MOLUS-KILL X BIDON 20 LITROS', 1959000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN MOLUS-KILL X GALON', 416800),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'GREEN MOLUS-KILL X LITRO', 110400),
-- IAS products (under RESO empresa)
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'FUNGY-BAC X BIDON 20 LITROS', 882889),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'FUNGY-BAC X LITRO', 47252),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'FUNGY-BAC X GALON', 184613),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'AJO AJI ORTIGA X GALON', 164084),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'AJO AJI ORTIGA X LITRO', 43251),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'AJO AJI ORTIGA X BIDON 20 LITROS', 779615),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'COOL PLANT X 25 KILOS', 621622),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'COOL PLANT X KILO', 27027),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CREOLINA X 20 LITROS', 336000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CREOLINA X 250 ML', 7200),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CREOLINA X GALON', 72000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CREOLINA X 500 ML', 12200),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'CREOLINA X LITRO', 19800),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NUTRICEL K50 X LITRO', 57230),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NUTRICEL K50 X BIDON 20 LITROS', 1063514),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NUTRICEL K50 X GALON', 218108),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ACTIV CEL X LITRO', 54054),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ACTIV CEL X BIDON 20 LITROS', 830067),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ACTIV CEL X GALON', 175405),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NUTRI ROOTS X 250 ML', 17432),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NUTRI ROOTS X BIDON 20 LITROS', 989189),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NUTRI ROOTS X GALON', 203243),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NUTRI ROOTS X LITRO', 53514),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'FERTI-HUMI 16 X BIDON 20 LITROS', 175676),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'FERTI-HUMI 16 X GALON', 43243),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'FERTI-HUMI 16 X LITRO', 12162),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NITRATO DE ZINC X 20 LITROS', 635135),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NITRATO DE ZINC X LITRO', 33784),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'HUMI 61 X KILO', 12162),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'HUMI 61 X 25 KILOS', 279730),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'VASTAGO 9-13-28 PRODUCCION X KILO', 12582),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'VASTAGO 9-13-28 PRODUCCION X 25 KILOS', 290236),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'URSUDOL X BLT 25 KILOS', 159179),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'URSUDOL X KILOS', 7340),
-- ABAGO products (under RESO empresa)
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'MALOLITA X KILO', 13700),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'MALOLITA X 25 KILOS', 318700),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'BORCAMAG X BIDON 20 LITROS', 412500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'BORCAMAG X GALON', 87500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'BORCAMAG X LITRO', 23700),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'BORCAMAG X 250 ML', 7500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'FUNBAC X LITRO', 46700),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'FUNBAC X GALON', 170000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'FUNBAC X BIDON 20 LITROS', 817500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ACI SI X 250 ML', 8100),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ACI SI X LITRO', 25600),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ACI SI X GALON', 95000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'ACI SI X BIDON 20 LITROS', 450000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'SABIAGRA X 250 ML', 9600),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'SABIAGRA X LITRO', 31200),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'SABIAGRA X GALON', 117500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'SABIAGRA X BIDON 20 LITROS', 437500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'MOSKAKILL X 250 ML', 24000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'MOSKAKILL X 500 ML', 42000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'MOSKAKILL X LITRO', 77500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'MOSKAKILL X GALON', 302500),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'MOSKAKILL X BIDON 20 LITROS', 1450000),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NUL X KILO', 10600),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'NUL X 25 KILOS', 250600),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'COMBI K X KILO', 13100),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'COMBI K X 25 KILOS', 309400),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'SOLUPOT K X KILO', 16200),
('SOLUCIONES INTEGRALES RESO SAS', 'Dealer', 'SOLUPOT K X 25 KILOS', 388700)
ON CONFLICT ("Empresa", "Tipo_Precio", "Producto") DO UPDATE
SET "Precio" = EXCLUDED."Precio",
    "updated_at" = now();
