-- ================================================================
-- Tabla: ListaPrecios (v2 - corrige Empresa a IASO, agrega Proveedor)
-- ================================================================

CREATE TABLE IF NOT EXISTS "ListaPrecios" (
  id bigserial PRIMARY KEY,
  "Empresa" text NOT NULL,
  "Tipo_Precio" text NOT NULL,
  "Producto" text NOT NULL,
  "Precio" numeric NOT NULL DEFAULT 0,
  "Proveedor" text DEFAULT '',
  "creado_por" uuid,
  "modificado_por" uuid,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- Agregar columna Proveedor si no existe (para tablas ya creadas)
ALTER TABLE "ListaPrecios" ADD COLUMN IF NOT EXISTS "Proveedor" text DEFAULT '';

-- Indices
CREATE INDEX IF NOT EXISTS idx_lista_precios_empresa_tipo
  ON "ListaPrecios" ("Empresa", "Tipo_Precio");

CREATE INDEX IF NOT EXISTS idx_lista_precios_producto
  ON "ListaPrecios" ("Producto");

-- Reemplazar constraint unico para incluir Proveedor
ALTER TABLE "ListaPrecios" DROP CONSTRAINT IF EXISTS uq_lista_precios_empresa_tipo_producto;
ALTER TABLE "ListaPrecios"
  ADD CONSTRAINT uq_lista_precios_empresa_tipo_producto
  UNIQUE ("Empresa", "Tipo_Precio", "Proveedor", "Producto");

-- RLS
ALTER TABLE "ListaPrecios" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ListaPrecios_select" ON "ListaPrecios";
DROP POLICY IF EXISTS "ListaPrecios_insert" ON "ListaPrecios";
DROP POLICY IF EXISTS "ListaPrecios_update" ON "ListaPrecios";
DROP POLICY IF EXISTS "ListaPrecios_delete" ON "ListaPrecios";

CREATE POLICY "ListaPrecios_select" ON "ListaPrecios"
  FOR SELECT USING (true);

CREATE POLICY "ListaPrecios_insert" ON "ListaPrecios"
  FOR INSERT WITH CHECK (true);

CREATE POLICY "ListaPrecios_update" ON "ListaPrecios"
  FOR UPDATE USING (true);

CREATE POLICY "ListaPrecios_delete" ON "ListaPrecios"
  FOR DELETE USING (true);

-- ================================================================
-- Datos: Lista de precios IASO - Dealer
-- Empresa = IASO, Proveedor = RESO / GREEN / IAS / ABAGO
-- ================================================================

-- Limpiar datos anteriores incorrectos (tenian Empresa = RESO)
DELETE FROM "ListaPrecios" WHERE "Empresa" = 'SOLUCIONES INTEGRALES RESO SAS';

INSERT INTO "ListaPrecios" ("Empresa", "Tipo_Precio", "Proveedor", "Producto", "Precio") VALUES
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GROW GREEN SP X BIDON 20 LITROS', 3204887),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GROW GREEN SP X GALON', 640977),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GROW GREEN SP X LITRO', 166654),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'IKASOL X BIDON 20 LITROS', 4026510),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'IKASOL X 250 ML', 55393),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'IKASOL X GALON', 810692),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'IKASOL X LITRO', 205373),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'ARACK GREEN X GALON', 580230),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'ARACK GREEN X 20 LITROS', 2874150),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'ARACK GREEN X 250 ML', 45405),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'ARACK GREEN X 500 ML', 78300),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'ARACK GREEN X LITRO', 147756),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'BA-BOR-ZINC X BIDON 20 LITROS', 2047567),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'BA-BOR-ZINC X 250 ML', 37390),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'BA-BOR-ZINC X GALON', 416641),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'BA-BOR-ZINC X 500 ML', 58832),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'BA-BOR-ZINC X LITRO', 110392),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'CALIMAN X GALON', 128196),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'CALIMAN X CANECA 10 LITROS', 291141),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'CALIMAN X BIDON 20 LITROS', 618980),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'CALIMAN X LITRO', 34720),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GEON3 X BIDON 20 LITROS', 1914300),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GEON3 X 250 ML', 27540),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GEON3 X GALON', 388260),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GEON3 X 500 ML', 51900),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GEON3 X LITRO', 99765),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GROW GREEN X LITRO', 138920),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GROW GREEN X 250 ML', 38780),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GROW GREEN X 500 ML', 74856),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GROW GREEN X GALON', 544887),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GROW GREEN X BIDON 20 LITROS', 2697435),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'JABOTAN X 20 LITROS', 507060),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'JABOTAN X GALON', 106811),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'JABOTAN X LITRO', 29403),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'NEEM GREEN X 500 ML', 83387),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'NEEM GREEN X BIDON 20 LITROS', 3026876),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'NEEM GREEN X 250 ML', 44943),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'NEEM GREEN X GALON', 614278),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'NEEM GREEN X LITRO', 156685),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'THYME GREEN X BIDON 20 LITROS', 3026876),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'THYME GREEN X 250 ML', 44943),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'THYME GREEN X LITRO', 156685),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'THYME GREEN X GALON', 614278),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'THYME GREEN X 500 ML', 83387),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'CALCI-TECH X GALON 5 LITROS', 85050),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'CALCI-TECH X LITRO', 24300),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'CALCI-TECH BIDON X 20 LITROS', 357750),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GENIUS-TECH X 250 ML', 34492),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GENIUS-TECH X GALON 5 LITROS', 494100),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GENIUS-TECH X BIDON 20 LITROS', 2443500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'GENIUS-TECH X LITRO', 127008),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'MEKA-TECH X 250 ML', 560250),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'MEKA-TECH X GALON 5 LITROS', 117450),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'MEKA-TECH X LITRO', 32400),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'NITRO-TECH X GALON 5 LITROS', 90450),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'NITRO-TECH X LITRO', 25650),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'NITRO-TECH X BIDON 20 LITROS', 425250),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'PROTO TECH X GALON 5 LITROS', 128250),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'PROTO TECH X LITRO', 35100),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'PROTO TECH X BIDON 20 LITROS', 614250),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'YODO X BIDON 20 LTS', 739791),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'YODO X GALON', 153358),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'YODO X LITRO', 41039),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'YODO X 250 ML', 14310),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'RESO', 'YODO X 500 ML', 22228),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN AMINO X BIDON 20 LITROS', 829227),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN AMINO X GALON', 175228),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN AMINO X LITRO', 46439),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN AMINO X 250 ML', 13365),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN FOS X 20 LITROS', 988188),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN FOS X 500 ML', 28755),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN FOS X GALON', 203037),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN FOS X LITRO', 53459),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN FOS X 250 ML', 17415),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN K X 500 ML', 34560),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN K X BIDON 20 LITROS', 1062437),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN K X GALON', 218887),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN K X LITRO', 57172),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN K X 250 ML', 18360),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CORRECTOR X 250 ML', 8580),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CORRECTOR X BIDON 20LT', 597624),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CORRECTOR X GALON', 121445),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CORRECTOR X LITRO', 33001),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN VAX X 500 ML', 50700),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN VAX X LITRO', 91000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CA-L X CANECA 10 LITROS', 308000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CA-L X CANECA 20 LITROS', 614000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CA-L X GALON', 128200),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CA-L X LITRO', 34800),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CA-L X CANECA 60 LITROS', 1810000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN 40F X BIDON 20 LITROS', 2697500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN 40F X 250 ML', 38800),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN 40F X 500 ML', 73500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN 40F X GALON', 545000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN 40F X LITRO', 138950),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'AKAR GREEN X 250 ML', 40900),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'AKAR GREEN X 500 ML', 79200),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'AKAR GREEN X BIDON 20 LITROS', 2874300),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'AKAR GREEN X GALON', 580300),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'AKAR GREEN X LITRO', 147800),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CU-ILL X BIDON 20 LITROS', 467800),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CU-ILL X GALON', 95150),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN CU-ILL X LITRO', 24300),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'PEGASSO TOP X BIDON 20 LITROS', 354000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'PEGASSO TOP X GALON', 71500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'PEGASSO TOP X LITRO', 18600),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'PEGASSO TOP X CANECA 60 LITROS', 998400),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'NEMOCAP X BIDON 20 LITROS', 1914300),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'NEMOCAP X 500 ML', 52000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'NEMOCAP X GALON', 388500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'NEMOCAP X LITRO', 99800),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'NEMOCAP X BIDON 60 LITROS', 5698000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'JABOTAN EXPORTACION X BIDON 20 LITROS', 677800),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'JABOTAN EXPORTACION X GALON', 142000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'JABOTAN EXPORTACION X LITRO', 39200),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'JABOTAN EXPORTACION X BIDON 60 LITROS', 2020000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN YODO X BIDON 20 LITROS', 739800),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN YODO X 250 ML', 14300),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN YODO X GALON', 153400),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN YODO X LITRO', 41000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN YODO X 500 ML', 25000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN MOLUS-KILL X 250 ML', 37400),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN MOLUS-KILL X 500 ML', 72400),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN MOLUS-KILL X BIDON 20 LITROS', 1959000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN MOLUS-KILL X GALON', 416800),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'GREEN', 'GREEN MOLUS-KILL X LITRO', 110400),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'FUNGY-BAC X BIDON 20 LITROS', 882889),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'FUNGY-BAC X LITRO', 47252),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'FUNGY-BAC X GALON', 184613),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'AJO AJI ORTIGA X GALON', 164084),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'AJO AJI ORTIGA X LITRO', 43251),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'AJO AJI ORTIGA X BIDON 20 LITROS', 779615),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'COOL PLANT X 25 KILOS', 621622),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'COOL PLANT X KILO', 27027),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'CREOLINA X 20 LITROS', 336000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'CREOLINA X 250 ML', 7200),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'CREOLINA X GALON', 72000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'CREOLINA X 500 ML', 12200),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'CREOLINA X LITRO', 19800),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'NUTRICEL K50 X LITRO', 57230),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'NUTRICEL K50 X BIDON 20 LITROS', 1063514),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'NUTRICEL K50 X GALON', 218108),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'ACTIV CEL X LITRO', 54054),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'ACTIV CEL X BIDON 20 LITROS', 830067),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'ACTIV CEL X GALON', 175405),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'NUTRI ROOTS X 250 ML', 17432),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'NUTRI ROOTS X BIDON 20 LITROS', 989189),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'NUTRI ROOTS X GALON', 203243),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'NUTRI ROOTS X LITRO', 53514),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'FERTI-HUMI 16 X BIDON 20 LITROS', 175676),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'FERTI-HUMI 16 X GALON', 43243),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'FERTI-HUMI 16 X LITRO', 12162),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'NITRATO DE ZINC X 20 LITROS', 635135),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'NITRATO DE ZINC X LITRO', 33784),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'HUMI 61 X KILO', 12162),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'HUMI 61 X 25 KILOS', 279730),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'VASTAGO 9-13-28 PRODUCCION X KILO', 12582),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'VASTAGO 9-13-28 PRODUCCION X 25 KILOS', 290236),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'URSUDOL X BLT 25 KILOS', 159179),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'IAS', 'URSUDOL X KILOS', 7340),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'MALOLITA X KILO', 13700),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'MALOLITA X 25 KILOS', 318700),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'BORCAMAG X BIDON 20 LITROS', 412500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'BORCAMAG X GALON', 87500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'BORCAMAG X LITRO', 23700),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'BORCAMAG X 250 ML', 7500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'CREOLINA X 20 LITROS', 350000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'CREOLINA X 250 ML', 7500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'CREOLINA X GALON', 75000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'CREOLINA X 500 ML', 7300),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'CREOLINA X LITRO', 20600),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'FUNBAC X LITRO', 46700),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'FUNBAC X GALON', 170000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'FUNBAC X BIDON 20 LITROS', 817500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'ACI SI X 250 ML', 8100),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'ACI SI X LITRO', 25600),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'ACI SI X GALON', 95000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'ACI SI X BIDON 20 LITROS', 450000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'SABIAGRA X 250 ML', 9600),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'SABIAGRA X LITRO', 31200),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'SABIAGRA X GALON', 117500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'SABIAGRA X BIDON 20 LITROS', 437500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'NITRO-TECH X 250 ML', 7900),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'NITRO-TECH X LITRO', 26200),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'NITRO-TECH X GALON', 97500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'NITRO-TECH X BIDON 20 LITROS', 462500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'MOSKAKILL X 250 ML', 24000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'MOSKAKILL X 500 ML', 42000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'MOSKAKILL X LITRO', 77500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'MOSKAKILL X GALON', 302500),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'MOSKAKILL X BIDON 20 LITROS', 1450000),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'NUL X KILO', 10600),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'NUL X 25 KILOS', 250600),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'COMBI K X KILO', 13100),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'COMBI K X 25 KILOS', 309400),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'SOLUPOT K X KILO', 16200),
('INSUMOS AGROPECUARIOS SOSTENIBLES SAS', 'Dealer', 'ABAGO', 'SOLUPOT K X 25 KILOS', 388700)
ON CONFLICT ("Empresa", "Tipo_Precio", "Proveedor", "Producto") DO UPDATE
SET "Precio" = EXCLUDED."Precio",
    "updated_at" = now();
